package plugin;

import plugin.signature.PluginSignatureVerifier;

import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.util.ArrayList;
import java.util.List;
import java.util.ServiceLoader;
import java.util.stream.Stream;

/**
 * Loads shape plugins from a directory or explicit JAR paths.
 * Verifies optional RSA signatures before exposing plugin classes.
 */
public final class PluginLoader {

  private final PluginSignatureVerifier verifier;
  private final boolean strictSignatures;

  /**
   * @param strictSignatures when true, only signed plugins are accepted
   */
  public PluginLoader(boolean strictSignatures) {
    this.strictSignatures = strictSignatures;
    this.verifier = new PluginSignatureVerifier(loadEmbeddedPublicKey(), strictSignatures);
  }

  /**
   * Loads RSA public key bytes packaged in {@code plugin-public.key} (generated by plugin-signer).
   *
   * @return Base64-encoded X.509 public key
   */
  /** @return Base64 RSA public key packaged with the application */
  public static String loadEmbeddedPublicKey() {
    try (var in = PluginLoader.class.getResourceAsStream("/plugin-public.key")) {
      if (in == null) {
        throw new IllegalStateException(
            "Missing plugin-public.key — run plugin-signer and copy keys/plugin-public.key to editor-app resources");
      }
      return new String(in.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8).trim();
    } catch (java.io.IOException e) {
      throw new IllegalStateException("Cannot read plugin-public.key", e);
    }
  }

  /**
   * Loads every {@code *.jar} from the plugins directory.
   *
   * @param pluginsDir directory containing plugin JARs
   * @return loaded shape plugins
   */
  public List<ShapePlugin> loadFromDirectory(Path pluginsDir) throws IOException {
    List<ShapePlugin> result = new ArrayList<>();
    if (!Files.isDirectory(pluginsDir)) {
      return result;
    }
    try (Stream<Path> stream = Files.list(pluginsDir)) {
      List<Path> jars = stream.filter(p -> p.toString().endsWith(".jar")).toList();
      for (Path jar : jars) {
        result.addAll(loadJar(jar));
      }
    }
    return result;
  }

  /**
   * Loads plugins from explicit JAR paths (e.g. command-line arguments).
   *
   * @param jarPaths one or more JAR file paths
   * @return loaded shape plugins
   */
  public List<ShapePlugin> loadFromPaths(String... jarPaths) throws IOException {
    List<ShapePlugin> result = new ArrayList<>();
    for (String path : jarPaths) {
      if (path != null && !path.isBlank()) {
        result.addAll(loadJar(Path.of(path)));
      }
    }
    return result;
  }

  /**
   * Loads a single plugin JAR after signature verification.
   *
   * @param jarPath path to plugin JAR
   * @return shape plugins declared in the JAR via {@link ServiceLoader}
   */
  public List<ShapePlugin> loadJar(Path jarPath) throws IOException {
    try {
      verifier.verify(jarPath);
    } catch (GeneralSecurityException ex) {
      if (strictSignatures) {
        throw new IOException("Plugin signature check failed: " + jarPath.getFileName(), ex);
      }
      System.err.println("Warning: loading unsigned plugin: " + jarPath.getFileName());
    }

    try {
      URL[] urls = {jarPath.toUri().toURL()};
      URLClassLoader loader =
          new URLClassLoader(urls, ShapePlugin.class.getClassLoader());
      ServiceLoader<ShapePlugin> serviceLoader =
          ServiceLoader.load(ShapePlugin.class, loader);
      List<ShapePlugin> plugins = new ArrayList<>();
      for (ShapePlugin plugin : serviceLoader) {
        plugins.add(plugin);
        System.out.println("Loaded shape plugin: " + plugin.getPluginId());
      }
      return plugins;
    } catch (Exception ex) {
      throw new IOException("Failed to load plugin JAR: " + jarPath, ex);
    }
  }
}
